name: Generate long-term charts (AIN-10 7d/1m/1y + stats)

on:
  workflow_dispatch:
  schedule:
    - cron: '20 21 * * 1-5'   # 16:20 ET (週日) → JST翌朝

permissions: { contents: write }

concurrency:
  group: ain10-long-${{ github.ref }}
  cancel-in-progress: false

jobs:
  long:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      INDEX_KEY: ain10
      OUT_DIR: docs/outputs
      MARKET_TZ: America/New_York
      SESSION_START: "09:30"
      SESSION_END:   "16:00"

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0, persist-credentials: true }

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # ① 履歴を追記（自動スケール補正を含む）
      - name: Append daily history
        run: python scripts/append_history.py

      # ② 長期チャートを描画（1d は別ワークフローがある想定なら出力しない）
      - name: Render 7d/1m/1y
        env:
          MARKET_TZ: ${{ env.MARKET_TZ }}
          SESSION_START: ${{ env.SESSION_START }}
          SESSION_END: ${{ env.SESSION_END }}
        run: |
          python scripts/long_charts.py
          date -u +"%Y-%m-%dT%H:%M:%SZ" > "$OUT_DIR/_last_run.txt"

      - name: Commit if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A docs/outputs
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "chore(ain10): append history and long-term charts"
            git push
          fi
