name: Generate long-term charts (1d/7d/1m/1y + stats + intraday)

on:
  workflow_dispatch:
  schedule:
    - cron: "15 20 * * *"   # UTC

permissions:
  contents: write

concurrency:
  group: long-charts-${{ github.ref }}
  cancel-in-progress: false

env:
  # ★ リポに合わせて変更可
  INDEX_KEY: ain10

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          set -e
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f src/requirements.txt ]; then
            pip install -r src/requirements.txt
          else
            pip install pandas numpy matplotlib
          fi

      - name: Generate long-term charts
        env:
          INDEX_KEY: ${{ env.INDEX_KEY }}
        run: |
          set -e
          python scripts/long_charts.py
          echo "---- LIST AFTER CHARTS ----"
          ls -al docs/outputs || true

      - name: Compute 1d % for X (update post & stats)
        env:
          INDEX_KEY: ${{ env.INDEX_KEY }}
        run: |
          set -e
          python scripts/ain10_pct_post.py
          echo "---- POST (preview) ----"
          cat docs/outputs/${INDEX_KEY}_post_intraday.txt || true
          echo "---- STATS (preview) ----"
          cat docs/outputs/${INDEX_KEY}_stats.json || true

      - name: Upload artifacts (for debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: docs/outputs

      - name: Commit charts if changed
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 画像（1d/7d/1m/1y）
          git add docs/outputs/${{ env.INDEX_KEY }}_1d.png || true
          git add docs/outputs/${{ env.INDEX_KEY }}_7d.png || true
          git add docs/outputs/${{ env.INDEX_KEY }}_1m.png || true
          git add docs/outputs/${{ env.INDEX_KEY }}_1y.png || true

          # CSV（生成されていれば）
          git add docs/outputs/${{ env.INDEX_KEY }}_1d.csv || true
          git add docs/outputs/${{ env.INDEX_KEY }}_7d.csv || true
          git add docs/outputs/${{ env.INDEX_KEY }}_1m.csv || true
          git add docs/outputs/${{ env.INDEX_KEY }}_1y.csv || true

          # stats と X 投稿用テキスト
          git add docs/outputs/${{ env.INDEX_KEY }}_stats.json        || true
          git add docs/outputs/${{ env.INDEX_KEY }}_post_intraday.txt || true

          if git diff --cached --quiet; then
            echo "No chart/stat updates."
            exit 0
          fi

          git commit -m "chore(charts): update ${{ env.INDEX_KEY }} (1d/7d/1m/1y + stats)"
          git push
