name: Generate long-term charts (1d/7d/1m/1y + stats + intraday)

on:
  workflow_dispatch:
  schedule:
    # 毎日 20:15 UTC（必要に応じて調整）
    - cron: "15 20 * * *"

permissions:
  contents: write

# 他WFとぶつからないよう強めにブロック
concurrency:
  group: ain10
  cancel-in-progress: true

env:
  INDEX_KEY: ain10
  THEME: dark              # "dark" / "light"
  # LINE_COLOR: "#ff6b6b"  # 必要なら上書き

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          set -e
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f src/requirements.txt ]; then
            pip install -r src/requirements.txt
          else
            pip install pandas numpy matplotlib
          fi

      # 画像/CSVだけを生成（post/statは触らない）
      - name: Generate long-term charts
        env:
          INDEX_KEY: ${{ env.INDEX_KEY }}
          THEME: ${{ env.THEME }}
          LINE_COLOR: ${{ env.LINE_COLOR }}
          WRITE_PLACEHOLDER: "0"
        run: |
          set -e
          python scripts/long_charts.py
          echo "---- LIST AFTER CHARTS ----"
          ls -al docs/outputs || true

      # 1日騰落率（open→latest）。post/stat はここだけが書く
      - name: Compute 1d percent & write posts
        env:
          INDEX_KEY: ${{ env.INDEX_KEY }}
        run: |
          set -e
          python scripts/ain10_pct_post.py \
            --index-key "${INDEX_KEY}" \
            --csv       "docs/outputs/${INDEX_KEY}_1d.csv" \
            --out-json  "docs/outputs/${INDEX_KEY}_stats.json" \
            --out-text  "docs/outputs/${INDEX_KEY}_post_intraday.txt"

      - name: Upload artifacts (for debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: docs/outputs

      - name: Commit charts if changed
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add docs/outputs/${{ env.INDEX_KEY }}_1d.png || true
          git add docs/outputs/${{ env.INDEX_KEY }}_7d.png || true
          git add docs/outputs/${{ env.INDEX_KEY }}_1m.png || true
          git add docs/outputs/${{ env.INDEX_KEY }}_1y.png || true

          git add docs/outputs/${{ env.INDEX_KEY }}_1d.csv || true
          git add docs/outputs/${{ env.INDEX_KEY }}_7d.csv || true
          git add docs/outputs/${{ env.INDEX_KEY }}_1m.csv || true
          git add docs/outputs/${{ env.INDEX_KEY }}_1y.csv || true

          git add docs/outputs/${{ env.INDEX_KEY }}_post_intraday.txt || true
          git add docs/outputs/${{ env.INDEX_KEY }}_stats.json || true

          if git diff --cached --quiet; then
            echo "No chart/stat updates."
            exit 0
          fi

          git commit -m "chore(charts): update ${{ env.INDEX_KEY }} (1d/7d/1m/1y + stats + intraday)"
          git push
