name: AIN-10 Intraday

permissions:
  contents: write

on:
  schedule:
    - cron: "35 21 * * *"  # 毎日 06:35 JST（= 前日 21:35 UTC）
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - name: Run AIN-10 intraday
        run: python src/ain10_intraday.py
      - name: Commit and push outputs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/outputs/*
          if ! git diff --cached --quiet; then
            git commit -m "Update AIN-10 intraday snapshot"
            git push
          fi
