name: AIN-10 Long Charts (manual + daily)

on:
  workflow_dispatch:
  schedule:
    - cron: '35 21 * * *'   # UTC 21:35 = JST 06:35

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INDEX_KEY: ain10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas matplotlib

      - name: List BEFORE
        run: |
          echo "INDEX_KEY=$INDEX_KEY"
          echo "----- BEFORE -----"
          ls -al docs/outputs || true

      - name: Generate long-term charts
        run: |
          python scripts/long_charts.py

      - name: List AFTER
        run: |
          echo "----- AFTER -----"
          ls -al docs/outputs || true
          echo "----- GIT STATUS -----"
          git status --porcelain

      - name: Upload artifacts (for debug)
        uses: actions/upload-artifact@v4
        with:
          name: ain10-longcharts
          path: |
            docs/outputs/*_7d.*
            docs/outputs/*_1m.*
            docs/outputs/*_1y.*

      - name: Commit charts if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(charts): update AIN-10 long-term charts (SMA & volume)"
          file_pattern: |
            docs/outputs/*_7d.png
            docs/outputs/*_1m.png
            docs/outputs/*_1y.png
            docs/outputs/*_7d.csv
            docs/outputs/*_1m.csv
            docs/outputs/*_1y.csv
