name: Generate long-term charts (1d/7d/1m/1y + volume)

on:
  workflow_dispatch:
  schedule:
    - cron: "15 20 * * *"  # UTC 時刻。必要に応じて調整

permissions:
  contents: write

concurrency:
  group: long-charts-${{ github.ref }}
  cancel-in-progress: false

env:
  # ★★ このリポに合わせて変更 ★★
  INDEX_KEY: ain10   # AIN-10: ain10 / Astra4: astra4 / S-COIN+: scoin_plus / R-BANK9: rbank9

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f src/requirements.txt ]; then
            pip install -r src/requirements.txt
          else
            pip install pandas numpy matplotlib
          fi

      - name: Generate long-term charts
        env:
          INDEX_KEY: ${{ env.INDEX_KEY }}
        run: |
          set -euo pipefail

          CSV_DIR="docs/outputs"
          OUT_DIR="docs/outputs"
          TITLE_PREFIX=$(printf "%s" "${INDEX_KEY}" | tr '[:lower:]' '[:upper:]')

          echo "---- INPUT CSVs ----"
          ls -al "${CSV_DIR}" || true

          python scripts/long_charts.py --csv "${CSV_DIR}/${INDEX_KEY}_1d.csv" --out "${OUT_DIR}/${INDEX_KEY}_1d.png" --title "${TITLE_PREFIX} (1d)"
          python scripts/long_charts.py --csv "${CSV_DIR}/${INDEX_KEY}_7d.csv" --out "${OUT_DIR}/${INDEX_KEY}_7d.png" --title "${TITLE_PREFIX} (7d)"
          python scripts/long_charts.py --csv "${CSV_DIR}/${INDEX_KEY}_1m.csv" --out "${OUT_DIR}/${INDEX_KEY}_1m.png" --title "${TITLE_PREFIX} (1m)"
          python scripts/long_charts.py --csv "${CSV_DIR}/${INDEX_KEY}_1y.csv" --out "${OUT_DIR}/${INDEX_KEY}_1y.png" --title "${TITLE_PREFIX} (1y)"

          echo "---- LIST AFTER ----"
          ls -al "${OUT_DIR}" || true

      - name: Upload artifacts (for debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: docs/outputs

      - name: Commit charts if changed
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 画像（1d/7d/1m/1y）
          git add docs/outputs/${{ env.INDEX_KEY }}_1d.png || true
          git add docs/outputs/${{ env.INDEX_KEY }}_7d.png || true
          git add docs/outputs/${{ env.INDEX_KEY }}_1m.png || true
          git add docs/outputs/${{ env.INDEX_KEY }}_1y.png || true

          # 任意: CSV（生成していなければ no-op）
          git add docs/outputs/${{ env.INDEX_KEY }}_1d.csv || true
          git add docs/outputs/${{ env.INDEX_KEY }}_7d.csv || true
          git add docs/outputs/${{ env.INDEX_KEY }}_1m.csv || true
          git add docs/outputs/${{ env.INDEX_KEY }}_1y.csv || true

          # ★ サイトが使う stats/marker も必ずコミット
          git add docs/outputs/${{ env.INDEX_KEY }}_stats.json        || true
          git add docs/outputs/${{ env.INDEX_KEY }}_post_intraday.txt || true

          if git diff --cached --quiet; then
            echo "No chart updates."
            exit 0
          fi

          git commit -m "chore(charts): update ${{ env.INDEX_KEY }} (1d/7d/1m/1y + stats)"
          git push
